function prettyfig()
% PRETTYFIG set asteatics of figures

set( gca, ...
    'FontName'   , 'Helvetica' ,...
    'FontSize'   , 10          ,...
    'LineWidth'  , 1           );

set( [get(gca,'title'), get(gca,'xlabel'), get(gca,'ylabel')], ...
    'FontName'   , 'AvantGarde');

set( get(gca,'title')          , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
    'Box'        , 'off'     , ...
    'TickDir'    , 'out'     , ...
    'TickLength' , [.02 .02] , ...
    'XMinorTick' , 'on'      , ...
    'YMinorTick' , 'on'      , ...
    'XColor'     , [.3 .3 .3], ...
    'YColor'     , [.3 .3 .3]);

end