function prettyfig()
% PRETTYFIG set asteatics of figures

set( gca, ...
    'FontName'   , 'Helvetica' ,...
    'FontSize'   , 10          ,...
    'LineWidth'  , 1           );

set( [get(gca,'Title'), get(gca,'XLabel'), get(gca,'YLabel')], ...
    'FontName'   , 'AvantGarde');

set( get(gca,'Title')          , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );

set(findall(gca,'Type','text') , ...
    'FontSize'   ,  10         , ...
    'FontName'   , 'Helvetica' );

set(gca, ...
    'Box'        , 'off'       , ...
    'TickDir'    , 'out'       , ...
    'TickLength' , [.02 .02]   , ...
    'XMinorTick' , 'on'        , ...
    'YMinorTick' , 'on'        , ...
    'XColor'     , [.3 .3 .3]  , ...
    'YColor'     , [.3 .3 .3]  );

set(gca, 'ColorOrder', linspecer(7));

% colormap(flipud(gray));

end

