function prettyfig()
% PRETTYFIG set asteatics of figures


set( gca, ...
    'FontName'   , 'Helvetica' ,...
    'FontSize'   , 12          ,...
    'LineWidth'  , 1           );

set( [get(gca,'Title'), get(gca,'XLabel'), get(gca,'YLabel')], ...
    'FontName'   , 'AvantGarde');

set( get(gca,'Title')          , ...
    'FontSize'   , 18          , ...
    'FontWeight' , 'bold'      );

set(findall(gca,'Type','text') , ...
    'FontSize'   ,  12         , ...
    'FontName'   , 'Helvetica' );

set(gca, ...
    'Box'        , 'off'       , ...
    'TickDir'    , 'out'       , ...
    'TickLength' , [.02 .02]   , ...
    'XMinorTick' , 'on'        , ...
    'YMinorTick' , 'on'        , ...
    'XColor'     , [.3 .3 .3]  , ...
    'YColor'     , [.3 .3 .3]  );

set(gca, 'ColorOrder', linspecer(7));

%# figure size printed on paper
set(gcf, 'PaperUnits','centimeters')
set(gcf, 'PaperSize',[8 8])
set(gcf, 'PaperOrientation','portrait')

% colormap(flipud(gray));

end

